//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_LOADING                     156
#define TITLE_INIT                      159
#define GWR_BASE                        161
#define GWR_01                          162
#define GWR_02                          163
#define BG1_BASE                        164
#define BG_02                           166
#define GM_03                           167
#define GM_00                           168
#define GM_01                           169
#define GM_02                           170
#define MWW_L                           173
#define MWW_R                           174
#define WWA_L                           175
#define WWA_R                           176
#define WWD                             177
#define WWH_L                           178
#define WWH_R                           179
#define WWJ_L                           180
#define WWJ_R                           181
#define WWL_1                           182
#define WWL_2                           183
#define WWL_3                           184
#define WWS_L                           185
#define WWS_R                           186
#define WWR_L1                          187
#define WWR_L2                          188
#define WWR_R1                          192
#define WWR_R2                          193
#define M_000                           194
#define M_001                           195
#define M_002                           196
#define M_003                           197
#define M_004                           198
#define M_005                           199
#define M_100                           200
#define M_101                           201
#define M_200                           202
#define M_201                           203
#define M_300                           204
#define M_400                           205
#define M_500                           206
#define M_501                           207
#define M_502                           208
#define M_503                           209
#define M_504                           210
#define M_505                           211
#define M_600                           212
#define M_601                           213
#define M_700                           214
#define M_800                           215
#define M_900                           216
#define M_901                           217
#define M_1000                          218
#define M_1100                          219
#define M_1101                          220
#define E_L0                            223
#define E_L1                            224
#define E_R0                            225
#define E_R1                            226
#define WEAPON_TEST                     227
#define BAT_0                           228
#define BAT_1                           229
#define SLIME_0                         230
#define SLIME_1                         231
#define SLIME_2                         232
#define BH_A0                           233
#define BH_A1                           234
#define BH_L0                           235
#define BH_L1                           236
#define BH_L2                           237
#define BH_R0                           238
#define BH_R1                           239
#define BH_R2                           240
#define BH_W0                           241
#define BH_W1                           242
#define BH_W2                           243
#define BH_W3                           244
#define BH_W4                           245
#define BH_W5                           246
#define BH_W6                           247
#define BH_W7                           248
#define SLIME_W0                        249
#define SLIME_W1                        250
#define SLIME_W2                        251
#define SLIME_W3                        252
#define SNAKE_1                         253
#define SNAKE_2                         254
#define SNAKE_3                         255
#define SNAKE_4                         256
#define SNAKE_0                         257
#define EYE_0                           258
#define EYE_1                           259
#define EYE_2                           260
#define EYE_3                           261
#define EYE_4                           262
#define EYE_5                           263
#define EYE_W1                          266
#define EYE_W2                          267
#define EYE_W3                          268
#define ORC_0                           269
#define ORC_1                           270
#define ORC_2                           271
#define ORC_3                           272
#define ORC_4                           273
#define ORC_5                           274
#define SKULL_0                         276
#define SKULL_1                         277
#define SKULL_2                         278
#define SKULL_3                         279
#define SKULL_4                         280
#define SKULL_5                         281
#define SKULL_6                         282
#define SKULL_7                         283
#define SKULL_W0                        284
#define SKULL_W1                        285
#define SKULL_W2                        286
#define SKULL_W3                        287
#define SKULL_W4                        288
#define SKULL_W5                        289
#define SKULL_W6                        290
#define SKULL_W7                        291
#define MBALL_0                         292
#define MBALL_1                         293
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        294
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
